### ISSUE TITLE
Does parlia consensus work running single validator node?

### ISSUE THREAD

**Issue by mohamedelshami** [bnb-chain/bsc-docker#2]
This bsc-docker is very helpful in getting private testnet BSC up and running in no time.

I was also looking for a way to run a single BSC node that acts as a validator and RPC at the same time for local development.

I've configured  [genesis](https://github.com/icon-project/btp/blob/btp_web3labs/devnet/docker/bsc-node/genesis.json) with a single sealer, and its the only account unlocked in Geth command options.

It appears however that as soon as epoch block is reached, the node halts with 'unauthorized validator' error - this indicates that the node is trying to rotate the sealer. 

So I'm not sure if what I'm trying to do is allowed by the consensus.

**Comment by steventranjs** [comment]
@mohamedelshami it seem the chainid of the genesis file is 97, which is `bsc testnet`
I think you need a genesis file of private network, just like the single node bsc  cluster in the bsc-docker

**Comment by mohamedelshami** [comment]
@steventranjs I don't think it matters for the private local node as long as chain Id remains consistent in both genesis and validators setup

**Comment by steventranjs** [comment]
@mohamedelshami  could u help to change the genesis to something rather than testnet ID? Cause it may sync with validator on testnet and cause problems
