### ISSUE TITLE
how to deploy cluster in different machines

### ISSUE THREAD

**Issue by jianchengwang** [bnb-chain/bsc-docker#3]
hello guys, I have 3 machines that want to build a cluster of BSC private chains, give me some ideas，thansk.

**Comment by tittuvarghese** [comment]
@jianchengwang  Are. you able to run on different machines? I'm also stuck at same place. Validator nodes on different machine is not connecting, on same machine it's working without any issues.

**Comment by jianchengwang** [comment]
> @jianchengwang Are. you able to run on different machines? I'm also stuck at same place. Validator nodes on different machine is not connecting, on same machine it's working without any issues.

not yet, if you solved it, give me a point, thanks

**Comment by stranbho** [comment]
@jianchengwang you need to expose port `30311` in both TCP & UDP

**Comment by steventranjs** [comment]
@jianchengwang I guess ur `30311` port is not open (or it's open but not UDP traffic)

**Comment by jianchengwang** [comment]
> @jianchengwang I guess ur `30311` port is not open (or it's open but not UDP traffic)

I make start-simple at the same machine, and bsc-rpc-node receive transaction but bsc-validatior-node not async transaction from bsc-rpc-node, so the transaction is always at pending， I don't know it is the matter about docker network or `.env.CLUSTER_CIDR`  config or not. can you share your bsc-docker repo or give me some ideas, thanks

**Comment by stranbho** [comment]
> 

@jianchengwang I've just sent email to ur yahoo mail, lets hv call to debug

**Comment by steventranjs** [comment]
Lets hv call to discuss, I've just sent email to ur yahoo mail

**Comment by tittuvarghese** [comment]
I have solved it and it's working. :) @jianchengwang  issues are related to following,

- Enable UDP and TCP 30311
- And remove the cidr restriction on bsc-rpc and bsc-validator sh files in the scripts folder. (--netrestrict ${CLUSTER_CIDR})
- Also enable UDP in the docker definition of RPC.

**Comment by tittuvarghese** [comment]
@steventranjs Any idea whether this implementation is same as BSC itself especially from the consensus perspective?

Like the top 21 who are staking the token would be elected as the validator.

**Comment by jianchengwang** [comment]
@tittuvarghese @steventranjs a new question, when I submit a transaction, the bsc-validator generate the new block successfully, but bsc-rpc occur error and shutdown, error log as follow:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf977b1]

goroutine 46 [running]:
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).applyTransaction(0xc000d5af00, 0x0, 0x0, 0x0, 0xc001d2fc50, 0x7fffffffffffffff, 0xc0017c8940, 0xc0017c8920, 0x0, 0x0, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:1181 +0x14f1
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).distributeToSystem(0xc000d5af00, 0xc0017c8920, 0xc000c9c780, 0xc0012358c0, 0x1b32878, 0xc0017c8840, 0xc00015c318, 0xc00015c360, 0x0, 0xc001235a90, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:1130 +0x1e5
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).distributeIncoming(0xc000d5af00, 0x0, 0x0, 0xc000000000, 0xc000c9c780, 0xc0012358c0, 0x1b32878, 0xc0017c8840, 0xc00015c318, 0xc00015c360, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:1060 +0x526
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).FinalizeAndAssemble(0xc000d5af00, 0x1b4a930, 0xc000d9c880, 0xc0012358c0, 0xc000c9c780, 0xc001d673b0, 0x2, 0x2, 0x263e138, 0x0, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:758 +0x496
github.com/ethereum/go-ethereum/miner.(*worker).commit(0xc000c36000, 0x263e138, 0x0, 0x0, 0x0, 0x0, 0xc06b218da3b9e3a6, 0x1e3b66e611, 0x2609d00, 0x203000, ...)
  github.com/ethereum/go-ethereum/miner/worker.go:997 +0x10a
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc000c36000, 0x0, 0x2609d01, 0x61cc0eb6)
  github.com/ethereum/go-ethereum/miner/worker.go:990 +0xa45
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc000c36000)
  github.com/ethereum/go-ethereum/miner/worker.go:526 +0x3a5
created by github.com/ethereum/go-ethereum/miner.newWorker
  github.com/ethereum/go-ethereum/miner/worker.go:234 +0x532```

**Comment by stranbho** [comment]
Thanks @tittuvarghese 
@jianchengwang you can set `CLUSTER_CIDR=0.0.0.0/0` to accept all incoming IPS but this is not recommended for production 

On ur new bug: it seem related to https://github.com/ethereum/go-ethereum/issues/22278
You just need to reset ur volume data and start from scratch again to fix

**Comment by steventranjs** [comment]
Thanks @tittuvarghese 
@jianchengwang you can set `CLUSTER_CIDR=0.0.0.0/0` to accept all peers but it's not recommended on production
On ur new crashed log, just need to reset all volume data & start from scratch again

**Comment by jianchengwang** [comment]
> Thanks @tittuvarghese @jianchengwang you can set `CLUSTER_CIDR=0.0.0.0/0` to accept all peers but it's not recommended on production On ur new crashed log, just need to reset all volume data & start from scratch again

I figure out the error reason, if the config set consensus to parlia and period = 0  , then I sendTransaction,  the bsc-rpc crashed. 
period = 3 just work fine.

**Comment by stranbho** [comment]
@jianchengwang welcome if u can make PR for this ;)
