### ISSUE TITLE
transaction pending

### ISSUE THREAD

**Issue by saclin** [bnb-chain/bsc-docker#5]
I set up private chain by Simple Validator Node Cluster.
so period is 3 by default, but sometime the block take long time to mint

![1642411459(1)](https://user-images.githubusercontent.com/30526808/149742803-f7d26de2-b9da-4cc3-9f8c-d5d200899431.png)

txpool:
  status: {
    pending: 472,
    queued: 0
  },

mining is true
> eth.mining
true

one of pending transaction:
        860: "0x25BaB421ea3D09842Aa0c7D7A181062084092A6D: 0 wei + 9000000 gas × 20000000000 wei"

**Comment by steventranjs** [comment]
@saclin it's may be because you set too much of gas price on ur transaction. What's the value of gas & gasPrice that you've put?
